apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: nx0x/apyton:latest  # Aquí usaremos la imagen que subiste a Docker Hub
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
