apiVersion: apps/v1
kind: Deployment
metadata:
  name: apyton-deployment
  labels:
    app: apyton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apyton
  template:
    metadata:
      labels:
        app: apyton
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: apyton
          image: nx0x/apyton:latest  # Imagen de la APU en DockerHub
          ports:
            - containerPort: 80  # Puerto en el que la API escucha
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "80Mi"
              cpu: "120m"
      nodeSelector:
        kubernetes.io/hostname: votan.interopera.jep.gov.co  # Nodo específico
---
apiVersion: v1
kind: Service
metadata:
  name: apyton-services
spec:
  selector:
    app: apyton
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apyton-virtualservice
spec:
  hosts:
    - "apyton"  # Nombre del servicio al que se dirige el tráfico
  http:
    - route:
        - destination:
            host: apyton
            port:
              number: 80
